services:
  prometheus:
    image: prom/prometheus:v2.38.0
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    hostname: prometheus

  node-exporter:
    image: prom/node-exporter:v1.3.1
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    container_name: exporter
    hostname: exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)


        #  alertmanager:
        #image: prom/alertmanager:v0.24.0
        #user: root
        #ports:
        #- 127.0.0.1:9093:9093
        #volumes:
        #- ./alertmanager/:/etc/alertmanager/
        #hostname: alertmanager
        #command:
        #- '--config.file=/etc/alertmanager/config.yml'
        #- '--storage.path=/etc/alertmanager/data'

  grafana:
    image: grafana/grafana:9.1.5
    user: root
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    hostname: grafana

  loki:
    image: grafana/loki:2.6.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.6.0
    volumes:
      - /var/log/nginx:/var/log/nginx
      - /var/log/apache2:/var/log/apache2
      - ./promtail:/etc/promtail
    command: -config.file=/etc/promtail/config.yml
