groups:
- name: high CPU alert from server 2
  rules:
  - alert: HostHighCpuLoad
    expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{instance="3.72.111.77:9100", mode="idle"}[1m])) * 100) > 70
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Host high CPU load (instance {{ $labels.instance }})
      description: "CPU load is > 70%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"



